version: 1.0.{build}
image: Visual Studio 2019
platform: x86
skip_tags: true
skip_branch_with_pr: true
clone_depth: 1

cache:
- c:\tools\vcpkg\installed\

install:
  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"'
  - cmd: git clone -b v2.1 --single-branch --depth=1 https://github.com/fiendish/LuaJIT.git C:\luajit
  - cmd: git clone --recurse --depth=1 https://github.com/fiendish/lua-openssl.git C:\lua-openssl

  - ps: |
      pushd C:\tools\vcpkg
      git pull
      .\bootstrap-vcpkg.bat
      vcpkg install openssl:x86-windows-static
      popd

  - ps: |
      pushd C:\
      Start-FileDownload 'https://github.com/fiendish/LuaJIT-build/releases/download/latest/lua51.lib'
      popd

  - ps: |
      pushd C:\lua-openssl
      git submodule update --init --recursive
      git submodule update --recursive
      (Get-Content Makefile.win) | ForEach-Object { $_ -replace '"' , '' } | Set-Content Makefile.win
      (Get-Content config.win) | ForEach-Object { $_ -replace '"' , '' } | Set-Content config.win
      (Get-Content config.win) | ForEach-Object { $_ -replace " /MD " , " /MT " } | Set-Content config.win
      (Get-Content config.win) | ForEach-Object { $_ -replace '^OPENSSL_INC=.*', 'OPENSSL_INC=C:\tools\vcpkg\installed\x86-windows-static\include' } | Set-Content config.win
      (Get-Content config.win) | ForEach-Object { $_ -replace '^OPENSSL_LIB=.*', 'OPENSSL_LIB=C:\tools\vcpkg\installed\x86-windows-static\lib\libcrypto.lib C:\tools\vcpkg\installed\x86-windows-static\lib\libssl.lib' } | Set-Content config.win
      (Get-Content config.win) | ForEach-Object { $_ -replace "LUA_INC=.+" , "LUA_INC=C:\luajit\src" } | Set-Content config.win
      (Get-Content config.win) | ForEach-Object { $_ -replace "LUA_LIB=.+" , "LUA_LIB=C:\lua51.lib" } | Set-Content config.win
      popd

  - cmd: nmake -f Makefile.win
  - ps: Get-ChildItem src\openssl.dll -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

before_deploy:
  - ps: |
      git config --global credential.helper store
      Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:auth_token):x-oauth-basic@github.com`n"
      git config --global user.name "fiendish"
      git config --global user.email "patcherton.fixesthings@gmail.com"

deploy:
  - provider: GitHub
    tag: latest
    auth_token:
      secure: /WceWguzAExHlMwJIOMl2MxPw+QmMne5MGQItu45rQ66xLoKLYGVQ8taqaLkrMYD
    artifact: /.*/
    force_update: true
