version: 1.0.{build}
image: Visual Studio 2015
skip_tags: true
skip_branch_with_pr: true
clone_depth: 1
install:
- cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86'
- cmd: git clone -b v2.1 --single-branch --depth=1 https://github.com/fiendish/LuaJIT.git C:\luajit
- cmd: git clone --recurse --depth=1 https://github.com/fiendish/lua-openssl.git c:\lua-openssl
- ps: pushd c:\luajit\src
- ps: (Get-Content msvcbuild.bat) | ForEach-Object { $_ -replace " /MD " , " /MT " } | Set-Content msvcbuild.bat
- cmd: ./msvcbuild.bat
- ps: |
      popd
      pushd C:\
      Start-FileDownload 'https://github.com/fiendish/LuaJIT-build/releases/download/latest/lua51.lib'
      popd
- ps: |
      pushd c:\lua-openssl
      (Get-Content Makefile.win) | ForEach-Object { $_ -replace '"' , '' } | Set-Content Makefile.win
      (Get-Content config.win) | ForEach-Object { $_ -replace '"' , '' } | Set-Content config.win
      (Get-Content config.win) | ForEach-Object { $_ -replace " /MD " , " /MT " } | Set-Content config.win
      (Get-Content config.win) | ForEach-Object { $_ -replace "libeay32" , "VC\static\libeay32MT" } | Set-Content config.win
      (Get-Content config.win) | ForEach-Object { $_ -replace "ssleay32" , "VC\static\ssleay32MT" } | Set-Content config.win
      (Get-Content config.win) | ForEach-Object { $_ -replace "LUA_INC=.+" , "LUA_INC=C:\luajit\src" } | Set-Content config.win
      (Get-Content config.win) | ForEach-Object { $_ -replace "LUA_LIB=.+" , "LUA_LIB=C:\lua51.lib" } | Set-Content config.win
- cmd: nmake -f Makefile.win
- cmd: copy src\openssl.dll C:\
- ps: |
      popd
      pushd C:\
      Get-ChildItem .\openssl.dll -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
build: off
before_deploy:
- ps: |
    git config --global credential.helper store
    Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:auth_token):x-oauth-basic@github.com`n"
    git config --global user.name "fiendish"
    git config --global user.email "patcherton.fixesthings@gmail.com"
deploy:
- provider: GitHub
  tag: latest
  auth_token:
    secure: /WceWguzAExHlMwJIOMl2MxPw+QmMne5MGQItu45rQ66xLoKLYGVQ8taqaLkrMYD
  artifact: /.*/
  force_update: true
