name: Build lua-openssl for Win32 static

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout lua-openssl
        uses: actions/checkout@v4
        with:
          repository: fiendish/lua-openssl
          path: lua-openssl
          submodules: recursive

      - name: Checkout LuaJIT
        uses: actions/checkout@v4
        with:
          repository: fiendish/LuaJIT
          ref: v2.1
          path: lua-openssl/LuaJIT
          submodules: recursive

      - name: Download prebuilt lua51.lib
        working-directory: lua-openssl
        run: |
          Invoke-WebRequest 'https://github.com/fiendish/LuaJIT-build/releases/download/latest/lua51.lib' -OutFile 'lua51.lib'

      - name: Set up MSVC x86 build environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Install vcpkg and OpenSSL
        working-directory: lua-openssl
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git vcpkg
          & vcpkg\bootstrap-vcpkg.bat
          vcpkg\vcpkg install openssl:x86-windows-static

      - name: Patch Makefile.win and config.win
        working-directory: lua-openssl
        run: |
          $opensslPath = "vcpkg\installed\x86-windows-static"
          (Get-Content Makefile.win) | ForEach-Object { $_ -replace '"', '' } | Set-Content Makefile.win
          (Get-Content config.win) | ForEach-Object { $_ -replace '"', '' } | Set-Content config.win
            (Get-Content config.win) | ForEach-Object { 
                $_ -replace " /MD ", " /MT " `
                   -replace " /MD$", " /MT" `
                   -replace " /MDd ", " /MTd " `
                   -replace " /MDd$", " /MTd" 
            } | Set-Content config.win
          (Get-Content config.win) | ForEach-Object { $_ -replace "LUA_INC=.+" , "LUA_INC=LuaJIT\src" } | Set-Content config.win
          (Get-Content config.win) | ForEach-Object { $_ -replace "LUA_LIB=.+" , "LUA_LIB=lua51.lib" } | Set-Content config.win
          (Get-Content config.win) | ForEach-Object { $_ -replace "OPENSSL_INC=.+" , "OPENSSL_INC=$opensslPath\include" } | Set-Content config.win
          (Get-Content config.win) | ForEach-Object { $_ -replace "OPENSSL_LIB=.+" , "OPENSSL_LIB=$opensslPath\lib\libssl.lib $opensslPath\lib\libcrypto.lib" } | Set-Content config.win
          Get-Content config.win
          Get-Content Makefile.win

      - name: Build lua-openssl
        working-directory: lua-openssl
        run: nmake -f Makefile.win

      - name: Create or update "latest" release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: lua-openssl/src/openssl.dll
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
